migrations_paths:
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
    'Bnza\JobManagerBundle\Migrations': 'vendor/bnza/job-manager2/migrations'
